---
- name: install packages {{ola_packages}}
  become: yes
  package: 
    name: "{{ola_packages}}"
  
- name: configure server
  become: yes
  template: 
    src: ola-server.conf.j2
    dest: /etc/ola/ola-server.conf

- name: configure startup
  become: yes
  copy: 
    src: etc/systemd/system/olad.service
    dest: /etc/systemd/system/olad.service
    mode: 0644
    owner: root
    group: root
  notify: kick systemd
  
- name: configure_plugins
  include_tasks: plugin.yml
  with_items: "{{_ola_plugins}}"
  loop_control:
    loop_var: plugin_name
    
- name: flush handlers
  meta: flush_handlers
