#! /bin/sh

export GIT_NAME=$(basename $PWD)
echo "Setting env for ansible in $GIT_NAME:"

#aliases
alias ap=ansible-playbook
alias av=ansible-vault
alias avv='ansible-vault view'
alias ave='ansible-vault edit'

export ANSIBLE_HOME=${PWD}
export ANSIBLE_INVENTORY=${PWD}/inventory
export ANSIBLE_RETRY_FILES_SAVE_PATH=/tmp/${GIT_NAME}

# check pass setup
if ! eval pass > /dev/null; then
  echo "install pass(1) on this host and initialize a vault ( pass init {{gpg_key_id}} )"
  return 1
elif ! pass ansible/$GIT_NAME/ansible_vault_password > /dev/null; then
  echo "  - creating vault password for $(basename $0):"
  pass insert ansible/$GIT_NAME/ansible_vault_password
fi

# setup to use pass(1) with vault passwords
export ANSIBLE_VAULT_PASSWORD_FILE=${PWD}/bin/ansible_vault_password

# setup VENV crap
export PYCURL_SSL_LIBRARY=openssl

# check for venv .. if not there.. look to see if we can make it
if [ ! -d venv -a -f Makefile ]; then
	echo "  - no venv .. found Makefile, running make"
	make
elif [ ! -d venv -a -f requirements.txt ]; then
	echo "  - no venv .. found requirements attempting to create":
	virtualenv venv
	pip install --no-cache-dir -r requirements.txt
fi

# set prompt 
export CONTEXT="($GIT_NAME)"
export PS1="($GIT_NAME)${PS1}"

. venv/bin/activate
  
