name: Release to Ansible Galaxy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  galaxy:
    runs-on: ubuntu-latest
    steps:
      - uses: robertdebock/galaxy-action@1.1.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
