---
fadecandy_step_config:
  listen:
    - null
    - 7890
  verbose: true
  color:
    gamma: 2.5
    whitepoint:
      - 0.7
      - 0.7
      - 0.7
  devices:
    - type: fadecandy
      serial: "{{ fc_serial }}"
      map: 
        - [ 0,    0,   0, 128 ]
        - [ 0,  120, 128, 128 ]
        - [ 0,  240, 256, 128 ]
        - [ 0,  360, 384, 128 ]
        - [ 0,  480, 512, 128 ]
        - [ 0,  540, 640, 128 ]
...