#!/bin/bash
### BEGIN INIT INFO
# Provides:          iwconfig
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: configures the wireless interface
/home/pi/pxdriver.py -d -u {{oid}} -p {{led_count}}
