---
- name: make sure usbutils is installed
  become: yes
  apt:
    state: present 
    name: usbutils

- name: get serial number
  become: yes
  changed_when: false  
  shell: 
    lsusb -d {{ fadecandy.usb_id }} -v | 
    grep iSerial | 
    awk '{ print $3 }'
  register: _fc_serial

- name: set fact
  set_fact:
    fc_serial: "{{ _fc_serial.stdout }}"

- name: write configuration
  become: yes
  notify: restart_fcserver
  template: 
    src: fcserver.json.j2
    dest: /usr/local/etc/fcserver.json


