show:
  vars:
    env_network: 172.18.1.0/24
    wifi_ssid: LIGHTS
  children:
    routers:
    sd_builder:
    props:

# groups
props:
  children: 
    scepters: 
    steps:

raspi:
  children:
    scepters:
    steps:

sceptres:
  hosts:
    sceptre-1:

steps:
  vars:
    network: "{{env_network | ipsubnet(27,2) }}"
    ansible_ssh_host: "{{ ipaddress }}"
    ansible_ssh_user: pi
    ola_port: 0
  hosts:
    ds-1:
      ipaddress: "{{network|ipaddr(0)|ipaddr('address')}}"
    ds-2:
      ipaddress: "{{network|ipaddr(1)|ipaddr('address')}}"
    ds-3:
      ipaddress: "{{network|ipaddr(2)|ipaddr('address')}}"
    ds-4:
      ipaddress: "{{network|ipaddr(3)|ipaddr('address')}}"
  
    cs-1a:
      ipaddress: "{{network|ipaddr(4)|ipaddr('address')}}"
    cs-1b:
      ipaddress: "{{network|ipaddr(5)|ipaddr('address')}}"
    cs-2:
      ipaddress: "{{network|ipaddr(6)|ipaddr('address')}}"
    cs-3:
      ipaddress: "{{network|ipaddr(7)|ipaddr('address')}}"
    cs-4a:
      ipaddress: "{{network|ipaddr(8)|ipaddr('address')}}"
    cs-4b:
      ipaddress: "{{network|ipaddr(9)|ipaddr('address')}}"

    us-1:
      ipaddress: "{{network|ipaddr(10)|ipaddr('address')}}"
    us-2:
      ipaddress: "{{network|ipaddr(11)|ipaddr('address')}}"

routers:
  hosts:
    gw.show:
      vars:
        ansible_ssh_host: 172.18.1.254
    gw.doghouse:
      vars:
        ansible_ssh_host: 172.18.1.1

