---
# https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=166355&p=1422254#p1420729
- name: make sure bonding tools are installed
  become: yes
  apt:
    state: present
    name: "{{bonding_packages}}"

- name: configure bonding for the kernel
  become: yes
  copy:
    dest: /etc/modprobe.d/bonding.conf
    content: "options bonding {{bonding_options | join(' ') }}\n"
  notify: reboot raspi

- name: configure network via /etc/network/interfaces
  become: yes
  template: 
    src: interfaces.j2
    dest: /etc/network/interfaces
  notify: reboot raspi

- name: configure startup arpping
  become: yes
  blockinfile:
    path: /etc/rc.local
    insertbefore: '^exit 0.*'
    block: 
      ( sleep 5; 
        arping -i eth0 -c 1 -S {{ansible_default_ipv4.address}} {{ansible_default_ipv4.gateway}} 2>&1 > /dev/null
      ) &
      dhclient -4 bond0
  notify: reboot raspi

- name: configure static ip from show ip if so configured
  become: yes
  when: show_dmx_ip is defined
  blockinfile:
    path: /etc/dhcpcd.conf
    block: |
      interface bond0
      static ip_address={{show_dmx_ip}}/{{ net_mask | ipaddr('prefix') }}
      static routers={{ansible_default_ipv4.gateway}}
      static domain_name_servers={{ansible_dns.nameservers | join(' ')}}
    

