---
- name: push SSH key if we have one
  authorized_keys:
    state: present
    exclusive: yes
    manage_dir: yes
    key: "{{secrets.users.root.authorized_key}}"
  when: " 'users' in secrets and
          'root' in secrets.users and
          'authorized_key' in secrets.users.root"
    
- name: set hostname
  hostname:
    name: "{{inventory_hostname}}"
  
- name: update the pi 
  apt:
     force: yes
     update_cache: yes
     cache_valid_time: 86400
  register: _apt_update
     
- name: upgrade if needed
  apt:
     upgrade: yes
  when: _apt_update is changed

- name: install packages
  apt: 
    name: "{{item}}"
  with_items: "{{apt_packages}}"

