---
- name: setup raspi config
  hosts: sd_builder
  gather_facts: no
  vars:
    iso_path: "/Users/branson/Documents/Images/2021-10-30-raspios-bullseye-armhf-lite.img"

  roles: 
    - sd_builder/image_burn
    - sd_builder/enable_ssh
    - sd_builder/configure_wifi
    - sd_builder/unmount_sd
        
