---
- name: setup raspi sd card
  hosts: sd_builder
  pre_tasks:
    - name: check age of iso
      stat: 
        path: "{{iso_path}}"
      register: _iso_file
       
  roles: 
    - sd_builder/image_burn
    - sd_builder/enable_ssh
    - sd_builder/configure_wifi
    - sd_builder/unmount_sd
        