ola_plugins:
  artnet:
    config:
      - enabled = true
      - always_broadcast = no
      - long_name = {{inventory_hostname}} ArtNet
      - short_name = {{inventory_hostname}} ArtNet 
  usbserial: 
    config: 
      - enabled = true
      - device_dir = dev
      - device_prefix = cu.usbserial-
      - device_prefix = ttyU
      - enabled = true
      - pro_fps_limit = 190
      - tri_use_raw_rdm = false
      - ultra_fps_limit = 40

dmx_fs:
  input:
    universe: 0
    plugin: artnet
  output:
    universe: 1
    plugin: Serial USB
    device: ultraDMX 
