---
- name: create /etc/ethers.d 
  raw:
    if [ ! -d /etc/ethers.d ]; then  \
      mkdir /etc/ethers.d; \
    fi

# this does not have to be in alpha order
- include_tasks: entry.yml
  loop: "{{hostnames}}"